# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from idm.api2.proto import \
    chats_service_pb2 as idm_dot_api2_dot_proto_dot_chats__service__pb2


class ChatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_chat = channel.unary_unary(
                '/idm.api2.proto.Chats/create_chat',
                request_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
                )
        self.get_chat = channel.unary_unary(
                '/idm.api2.proto.Chats/get_chat',
                request_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.GetChatRequest.SerializeToString,
                response_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
                )
        self.list_chats = channel.unary_unary(
                '/idm.api2.proto.Chats/list_chats',
                request_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ListChatsRequest.SerializeToString,
                response_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatsData.FromString,
                )
        self.update_chat = channel.unary_unary(
                '/idm.api2.proto.Chats/update_chat',
                request_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.UpdateChatRequest.SerializeToString,
                response_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
                )


class ChatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_chats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_chat': grpc.unary_unary_rpc_method_handler(
                    servicer.create_chat,
                    request_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.CreateChatRequest.FromString,
                    response_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.SerializeToString,
            ),
            'get_chat': grpc.unary_unary_rpc_method_handler(
                    servicer.get_chat,
                    request_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.GetChatRequest.FromString,
                    response_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.SerializeToString,
            ),
            'list_chats': grpc.unary_unary_rpc_method_handler(
                    servicer.list_chats,
                    request_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ListChatsRequest.FromString,
                    response_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatsData.SerializeToString,
            ),
            'update_chat': grpc.unary_unary_rpc_method_handler(
                    servicer.update_chat,
                    request_deserializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.UpdateChatRequest.FromString,
                    response_serializer=idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'idm.api2.proto.Chats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.api2.proto.Chats/create_chat',
            idm_dot_api2_dot_proto_dot_chats__service__pb2.CreateChatRequest.SerializeToString,
            idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.api2.proto.Chats/get_chat',
            idm_dot_api2_dot_proto_dot_chats__service__pb2.GetChatRequest.SerializeToString,
            idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_chats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.api2.proto.Chats/list_chats',
            idm_dot_api2_dot_proto_dot_chats__service__pb2.ListChatsRequest.SerializeToString,
            idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatsData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.api2.proto.Chats/update_chat',
            idm_dot_api2_dot_proto_dot_chats__service__pb2.UpdateChatRequest.SerializeToString,
            idm_dot_api2_dot_proto_dot_chats__service__pb2.ChatData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
