// source: nexus/models/proto/operation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nexus_models_proto_typed_document_pb = require('../../../nexus/models/proto/typed_document_pb.js');
goog.object.extend(proto, nexus_models_proto_typed_document_pb);
goog.exportSymbol('proto.nexus.models.proto.CrossReferenceOperation', null, global);
goog.exportSymbol('proto.nexus.models.proto.DocumentOperation', null, global);
goog.exportSymbol('proto.nexus.models.proto.DocumentOperation.OperationCase', null, global);
goog.exportSymbol('proto.nexus.models.proto.UpdateDocument', null, global);
goog.exportSymbol('proto.nexus.models.proto.Vote', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.CrossReferenceOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.models.proto.CrossReferenceOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.CrossReferenceOperation.displayName = 'proto.nexus.models.proto.CrossReferenceOperation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.DocumentOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.nexus.models.proto.DocumentOperation.oneofGroups_);
};
goog.inherits(proto.nexus.models.proto.DocumentOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.DocumentOperation.displayName = 'proto.nexus.models.proto.DocumentOperation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.Vote = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.models.proto.Vote, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.Vote.displayName = 'proto.nexus.models.proto.Vote';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.UpdateDocument = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.models.proto.UpdateDocument.repeatedFields_, null);
};
goog.inherits(proto.nexus.models.proto.UpdateDocument, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.UpdateDocument.displayName = 'proto.nexus.models.proto.UpdateDocument';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.CrossReferenceOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.CrossReferenceOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.CrossReferenceOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: jspb.Message.getFieldWithDefault(msg, 1, ""),
    target: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastRetryUnixtime: jspb.Message.getFieldWithDefault(msg, 3, 0),
    retryCount: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.CrossReferenceOperation}
 */
proto.nexus.models.proto.CrossReferenceOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.CrossReferenceOperation;
  return proto.nexus.models.proto.CrossReferenceOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.CrossReferenceOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.CrossReferenceOperation}
 */
proto.nexus.models.proto.CrossReferenceOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLastRetryUnixtime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRetryCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.CrossReferenceOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.CrossReferenceOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.CrossReferenceOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTarget();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastRetryUnixtime();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getRetryCount();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional string source = 1;
 * @return {string}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.CrossReferenceOperation} returns this
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string target = 2;
 * @return {string}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.CrossReferenceOperation} returns this
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.setTarget = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 last_retry_unixtime = 3;
 * @return {number}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.getLastRetryUnixtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.CrossReferenceOperation} returns this
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.setLastRetryUnixtime = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 retry_count = 4;
 * @return {number}
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.getRetryCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.CrossReferenceOperation} returns this
 */
proto.nexus.models.proto.CrossReferenceOperation.prototype.setRetryCount = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.nexus.models.proto.DocumentOperation.oneofGroups_ = [[1,3]];

/**
 * @enum {number}
 */
proto.nexus.models.proto.DocumentOperation.OperationCase = {
  OPERATION_NOT_SET: 0,
  VOTE: 1,
  UPDATE_DOCUMENT: 3
};

/**
 * @return {proto.nexus.models.proto.DocumentOperation.OperationCase}
 */
proto.nexus.models.proto.DocumentOperation.prototype.getOperationCase = function() {
  return /** @type {proto.nexus.models.proto.DocumentOperation.OperationCase} */(jspb.Message.computeOneofCase(this, proto.nexus.models.proto.DocumentOperation.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.DocumentOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.DocumentOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.DocumentOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.DocumentOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    vote: (f = msg.getVote()) && proto.nexus.models.proto.Vote.toObject(includeInstance, f),
    updateDocument: (f = msg.getUpdateDocument()) && proto.nexus.models.proto.UpdateDocument.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.DocumentOperation}
 */
proto.nexus.models.proto.DocumentOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.DocumentOperation;
  return proto.nexus.models.proto.DocumentOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.DocumentOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.DocumentOperation}
 */
proto.nexus.models.proto.DocumentOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.nexus.models.proto.Vote;
      reader.readMessage(value,proto.nexus.models.proto.Vote.deserializeBinaryFromReader);
      msg.setVote(value);
      break;
    case 3:
      var value = new proto.nexus.models.proto.UpdateDocument;
      reader.readMessage(value,proto.nexus.models.proto.UpdateDocument.deserializeBinaryFromReader);
      msg.setUpdateDocument(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.DocumentOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.DocumentOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.DocumentOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.DocumentOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVote();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.nexus.models.proto.Vote.serializeBinaryToWriter
    );
  }
  f = message.getUpdateDocument();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.nexus.models.proto.UpdateDocument.serializeBinaryToWriter
    );
  }
};


/**
 * optional Vote vote = 1;
 * @return {?proto.nexus.models.proto.Vote}
 */
proto.nexus.models.proto.DocumentOperation.prototype.getVote = function() {
  return /** @type{?proto.nexus.models.proto.Vote} */ (
    jspb.Message.getWrapperField(this, proto.nexus.models.proto.Vote, 1));
};


/**
 * @param {?proto.nexus.models.proto.Vote|undefined} value
 * @return {!proto.nexus.models.proto.DocumentOperation} returns this
*/
proto.nexus.models.proto.DocumentOperation.prototype.setVote = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.nexus.models.proto.DocumentOperation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.DocumentOperation} returns this
 */
proto.nexus.models.proto.DocumentOperation.prototype.clearVote = function() {
  return this.setVote(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.DocumentOperation.prototype.hasVote = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional UpdateDocument update_document = 3;
 * @return {?proto.nexus.models.proto.UpdateDocument}
 */
proto.nexus.models.proto.DocumentOperation.prototype.getUpdateDocument = function() {
  return /** @type{?proto.nexus.models.proto.UpdateDocument} */ (
    jspb.Message.getWrapperField(this, proto.nexus.models.proto.UpdateDocument, 3));
};


/**
 * @param {?proto.nexus.models.proto.UpdateDocument|undefined} value
 * @return {!proto.nexus.models.proto.DocumentOperation} returns this
*/
proto.nexus.models.proto.DocumentOperation.prototype.setUpdateDocument = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.nexus.models.proto.DocumentOperation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.DocumentOperation} returns this
 */
proto.nexus.models.proto.DocumentOperation.prototype.clearUpdateDocument = function() {
  return this.setUpdateDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.DocumentOperation.prototype.hasUpdateDocument = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.Vote.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.Vote.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.Vote} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Vote.toObject = function(includeInstance, msg) {
  var f, obj = {
    documentId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFieldWithDefault(msg, 2, 0),
    voterId: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.Vote}
 */
proto.nexus.models.proto.Vote.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.Vote;
  return proto.nexus.models.proto.Vote.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.Vote} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.Vote}
 */
proto.nexus.models.proto.Vote.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVoterId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.Vote.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.Vote.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.Vote} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Vote.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocumentId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getVoterId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int64 document_id = 1;
 * @return {number}
 */
proto.nexus.models.proto.Vote.prototype.getDocumentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Vote} returns this
 */
proto.nexus.models.proto.Vote.prototype.setDocumentId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 value = 2;
 * @return {number}
 */
proto.nexus.models.proto.Vote.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Vote} returns this
 */
proto.nexus.models.proto.Vote.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 voter_id = 3;
 * @return {number}
 */
proto.nexus.models.proto.Vote.prototype.getVoterId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Vote} returns this
 */
proto.nexus.models.proto.Vote.prototype.setVoterId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.models.proto.UpdateDocument.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.UpdateDocument.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.UpdateDocument.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.UpdateDocument} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.UpdateDocument.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    shouldFillFromExternalSource: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    commit: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    reindex: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    typedDocument: (f = msg.getTypedDocument()) && nexus_models_proto_typed_document_pb.TypedDocument.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.UpdateDocument}
 */
proto.nexus.models.proto.UpdateDocument.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.UpdateDocument;
  return proto.nexus.models.proto.UpdateDocument.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.UpdateDocument} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.UpdateDocument}
 */
proto.nexus.models.proto.UpdateDocument.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFields(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShouldFillFromExternalSource(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCommit(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReindex(value);
      break;
    case 5:
      var value = new nexus_models_proto_typed_document_pb.TypedDocument;
      reader.readMessage(value,nexus_models_proto_typed_document_pb.TypedDocument.deserializeBinaryFromReader);
      msg.setTypedDocument(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.UpdateDocument.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.UpdateDocument.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.UpdateDocument} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.UpdateDocument.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getShouldFillFromExternalSource();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCommit();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getReindex();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTypedDocument();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      nexus_models_proto_typed_document_pb.TypedDocument.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string fields = 1;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.UpdateDocument.prototype.getFieldsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.setFieldsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.addFields = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.clearFieldsList = function() {
  return this.setFieldsList([]);
};


/**
 * optional bool should_fill_from_external_source = 2;
 * @return {boolean}
 */
proto.nexus.models.proto.UpdateDocument.prototype.getShouldFillFromExternalSource = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.setShouldFillFromExternalSource = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool commit = 3;
 * @return {boolean}
 */
proto.nexus.models.proto.UpdateDocument.prototype.getCommit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.setCommit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool reindex = 4;
 * @return {boolean}
 */
proto.nexus.models.proto.UpdateDocument.prototype.getReindex = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.setReindex = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional TypedDocument typed_document = 5;
 * @return {?proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.models.proto.UpdateDocument.prototype.getTypedDocument = function() {
  return /** @type{?proto.nexus.models.proto.TypedDocument} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_typed_document_pb.TypedDocument, 5));
};


/**
 * @param {?proto.nexus.models.proto.TypedDocument|undefined} value
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
*/
proto.nexus.models.proto.UpdateDocument.prototype.setTypedDocument = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.UpdateDocument} returns this
 */
proto.nexus.models.proto.UpdateDocument.prototype.clearTypedDocument = function() {
  return this.setTypedDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.UpdateDocument.prototype.hasTypedDocument = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.nexus.models.proto);
