// source: nexus/models/proto/scimag.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.nexus.models.proto.Scimag', null, global);
goog.exportSymbol('proto.nexus.models.proto.Scimag.OptionalIssuedAtCase', null, global);
goog.exportSymbol('proto.nexus.models.proto.Scimag.OptionalScimagBulkIdCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.Scimag = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.models.proto.Scimag.repeatedFields_, proto.nexus.models.proto.Scimag.oneofGroups_);
};
goog.inherits(proto.nexus.models.proto.Scimag, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.Scimag.displayName = 'proto.nexus.models.proto.Scimag';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.models.proto.Scimag.repeatedFields_ = [3,31,25,28,17];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.nexus.models.proto.Scimag.oneofGroups_ = [[26],[24]];

/**
 * @enum {number}
 */
proto.nexus.models.proto.Scimag.OptionalIssuedAtCase = {
  OPTIONAL_ISSUED_AT_NOT_SET: 0,
  ISSUED_AT: 26
};

/**
 * @return {proto.nexus.models.proto.Scimag.OptionalIssuedAtCase}
 */
proto.nexus.models.proto.Scimag.prototype.getOptionalIssuedAtCase = function() {
  return /** @type {proto.nexus.models.proto.Scimag.OptionalIssuedAtCase} */(jspb.Message.computeOneofCase(this, proto.nexus.models.proto.Scimag.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.nexus.models.proto.Scimag.OptionalScimagBulkIdCase = {
  OPTIONAL_SCIMAG_BULK_ID_NOT_SET: 0,
  SCIMAG_BULK_ID: 24
};

/**
 * @return {proto.nexus.models.proto.Scimag.OptionalScimagBulkIdCase}
 */
proto.nexus.models.proto.Scimag.prototype.getOptionalScimagBulkIdCase = function() {
  return /** @type {proto.nexus.models.proto.Scimag.OptionalScimagBulkIdCase} */(jspb.Message.computeOneofCase(this, proto.nexus.models.proto.Scimag.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.Scimag.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.Scimag.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.Scimag} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Scimag.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pb_abstract: jspb.Message.getFieldWithDefault(msg, 2, ""),
    authorsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    containerTitle: jspb.Message.getFieldWithDefault(msg, 11, ""),
    doi: jspb.Message.getFieldWithDefault(msg, 4, ""),
    downloadsCount: jspb.Message.getFieldWithDefault(msg, 27, 0),
    embedding: msg.getEmbedding_asB64(),
    filesize: jspb.Message.getFieldWithDefault(msg, 5, 0),
    firstPage: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ipfsMultihashesList: (f = jspb.Message.getRepeatedField(msg, 31)) == null ? undefined : f,
    isDeleted: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    issnsList: (f = jspb.Message.getRepeatedField(msg, 25)) == null ? undefined : f,
    issue: jspb.Message.getFieldWithDefault(msg, 10, ""),
    issuedAt: jspb.Message.getFieldWithDefault(msg, 26, 0),
    journalId: jspb.Message.getFieldWithDefault(msg, 12, 0),
    language: jspb.Message.getFieldWithDefault(msg, 13, ""),
    lastPage: jspb.Message.getFieldWithDefault(msg, 14, 0),
    metaLanguage: jspb.Message.getFieldWithDefault(msg, 15, ""),
    md5: jspb.Message.getFieldWithDefault(msg, 16, ""),
    refByCount: jspb.Message.getFieldWithDefault(msg, 23, 0),
    referencesList: (f = jspb.Message.getRepeatedField(msg, 28)) == null ? undefined : f,
    scimagBulkId: jspb.Message.getFieldWithDefault(msg, 24, 0),
    tagsList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    telegramFileId: jspb.Message.getFieldWithDefault(msg, 18, ""),
    title: jspb.Message.getFieldWithDefault(msg, 19, ""),
    type: jspb.Message.getFieldWithDefault(msg, 29, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 20, 0),
    volume: jspb.Message.getFieldWithDefault(msg, 21, ""),
    year: jspb.Message.getFieldWithDefault(msg, 30, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.Scimag}
 */
proto.nexus.models.proto.Scimag.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.Scimag;
  return proto.nexus.models.proto.Scimag.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.Scimag} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.Scimag}
 */
proto.nexus.models.proto.Scimag.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAbstract(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addAuthors(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setContainerTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDoi(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDownloadsCount(value);
      break;
    case 22:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEmbedding(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFilesize(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFirstPage(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.addIpfsMultihashes(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDeleted(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.addIssns(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssue(value);
      break;
    case 26:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIssuedAt(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setJournalId(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLastPage(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setMetaLanguage(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setMd5(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRefByCount(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.addReferences(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScimagBulkId(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setTelegramFileId(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUpdatedAt(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setYear(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.Scimag.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.Scimag.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.Scimag} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Scimag.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAbstract();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAuthorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getContainerTitle();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getDoi();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDownloadsCount();
  if (f !== 0) {
    writer.writeUint32(
      27,
      f
    );
  }
  f = message.getEmbedding_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      22,
      f
    );
  }
  f = message.getFilesize();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getFirstPage();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getIpfsMultihashesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      31,
      f
    );
  }
  f = message.getIsDeleted();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getIssnsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      25,
      f
    );
  }
  f = message.getIssue();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 26));
  if (f != null) {
    writer.writeInt64(
      26,
      f
    );
  }
  f = message.getJournalId();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getLastPage();
  if (f !== 0) {
    writer.writeUint32(
      14,
      f
    );
  }
  f = message.getMetaLanguage();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getMd5();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getRefByCount();
  if (f !== 0) {
    writer.writeInt32(
      23,
      f
    );
  }
  f = message.getReferencesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      28,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 24));
  if (f != null) {
    writer.writeInt32(
      24,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getTelegramFileId();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = message.getVolume();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getYear();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string abstract = 2;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getAbstract = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setAbstract = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string authors = 3;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Scimag.prototype.getAuthorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setAuthorsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.addAuthors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearAuthorsList = function() {
  return this.setAuthorsList([]);
};


/**
 * optional string container_title = 11;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getContainerTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setContainerTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string doi = 4;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getDoi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setDoi = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint32 downloads_count = 27;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getDownloadsCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setDownloadsCount = function(value) {
  return jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional bytes embedding = 22;
 * @return {!(string|Uint8Array)}
 */
proto.nexus.models.proto.Scimag.prototype.getEmbedding = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * optional bytes embedding = 22;
 * This is a type-conversion wrapper around `getEmbedding()`
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getEmbedding_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEmbedding()));
};


/**
 * optional bytes embedding = 22;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEmbedding()`
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.Scimag.prototype.getEmbedding_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEmbedding()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setEmbedding = function(value) {
  return jspb.Message.setProto3BytesField(this, 22, value);
};


/**
 * optional uint32 filesize = 5;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getFilesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setFilesize = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 first_page = 6;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getFirstPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setFirstPage = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated string ipfs_multihashes = 31;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Scimag.prototype.getIpfsMultihashesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 31));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setIpfsMultihashesList = function(value) {
  return jspb.Message.setField(this, 31, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.addIpfsMultihashes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 31, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearIpfsMultihashesList = function() {
  return this.setIpfsMultihashesList([]);
};


/**
 * optional bool is_deleted = 7;
 * @return {boolean}
 */
proto.nexus.models.proto.Scimag.prototype.getIsDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setIsDeleted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * repeated string issns = 25;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Scimag.prototype.getIssnsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 25));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setIssnsList = function(value) {
  return jspb.Message.setField(this, 25, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.addIssns = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 25, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearIssnsList = function() {
  return this.setIssnsList([]);
};


/**
 * optional string issue = 10;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getIssue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setIssue = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional int64 issued_at = 26;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getIssuedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setIssuedAt = function(value) {
  return jspb.Message.setOneofField(this, 26, proto.nexus.models.proto.Scimag.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearIssuedAt = function() {
  return jspb.Message.setOneofField(this, 26, proto.nexus.models.proto.Scimag.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.Scimag.prototype.hasIssuedAt = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional uint32 journal_id = 12;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getJournalId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setJournalId = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string language = 13;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional uint32 last_page = 14;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getLastPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setLastPage = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional string meta_language = 15;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getMetaLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setMetaLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string md5 = 16;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getMd5 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setMd5 = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional int32 ref_by_count = 23;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getRefByCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setRefByCount = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * repeated string references = 28;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Scimag.prototype.getReferencesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 28));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setReferencesList = function(value) {
  return jspb.Message.setField(this, 28, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.addReferences = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 28, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearReferencesList = function() {
  return this.setReferencesList([]);
};


/**
 * optional int32 scimag_bulk_id = 24;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getScimagBulkId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setScimagBulkId = function(value) {
  return jspb.Message.setOneofField(this, 24, proto.nexus.models.proto.Scimag.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearScimagBulkId = function() {
  return jspb.Message.setOneofField(this, 24, proto.nexus.models.proto.Scimag.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.Scimag.prototype.hasScimagBulkId = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * repeated string tags = 17;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Scimag.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};


/**
 * optional string telegram_file_id = 18;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getTelegramFileId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setTelegramFileId = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string title = 19;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string type = 29;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 29, value);
};


/**
 * optional int32 updated_at = 20;
 * @return {number}
 */
proto.nexus.models.proto.Scimag.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional string volume = 21;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setVolume = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string year = 30;
 * @return {string}
 */
proto.nexus.models.proto.Scimag.prototype.getYear = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Scimag} returns this
 */
proto.nexus.models.proto.Scimag.prototype.setYear = function(value) {
  return jspb.Message.setProto3StringField(this, 30, value);
};


goog.object.extend(exports, proto.nexus.models.proto);
