// source: nexus/models/proto/sharience.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.nexus.models.proto.Sharience', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.Sharience = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.models.proto.Sharience.repeatedFields_, null);
};
goog.inherits(proto.nexus.models.proto.Sharience, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.Sharience.displayName = 'proto.nexus.models.proto.Sharience';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.models.proto.Sharience.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.Sharience.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.Sharience.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.Sharience} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Sharience.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    parentId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    uploaderId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    md5: jspb.Message.getFieldWithDefault(msg, 5, ""),
    filesize: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ipfsMultihashesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    telegramFileId: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.Sharience}
 */
proto.nexus.models.proto.Sharience.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.Sharience;
  return proto.nexus.models.proto.Sharience.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.Sharience} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.Sharience}
 */
proto.nexus.models.proto.Sharience.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setParentId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUploaderId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUpdatedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMd5(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFilesize(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addIpfsMultihashes(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTelegramFileId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.Sharience.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.Sharience.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.Sharience} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.Sharience.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getParentId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getUploaderId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getMd5();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFilesize();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getIpfsMultihashesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getTelegramFileId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.nexus.models.proto.Sharience.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 parent_id = 2;
 * @return {number}
 */
proto.nexus.models.proto.Sharience.prototype.getParentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setParentId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 uploader_id = 3;
 * @return {number}
 */
proto.nexus.models.proto.Sharience.prototype.getUploaderId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setUploaderId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 updated_at = 4;
 * @return {number}
 */
proto.nexus.models.proto.Sharience.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string md5 = 5;
 * @return {string}
 */
proto.nexus.models.proto.Sharience.prototype.getMd5 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setMd5 = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 filesize = 6;
 * @return {number}
 */
proto.nexus.models.proto.Sharience.prototype.getFilesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setFilesize = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated string ipfs_multihashes = 7;
 * @return {!Array<string>}
 */
proto.nexus.models.proto.Sharience.prototype.getIpfsMultihashesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setIpfsMultihashesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.addIpfsMultihashes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.clearIpfsMultihashesList = function() {
  return this.setIpfsMultihashesList([]);
};


/**
 * optional string telegram_file_id = 8;
 * @return {string}
 */
proto.nexus.models.proto.Sharience.prototype.getTelegramFileId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.models.proto.Sharience} returns this
 */
proto.nexus.models.proto.Sharience.prototype.setTelegramFileId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


goog.object.extend(exports, proto.nexus.models.proto);
