# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexus/models/proto/typed_document.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nexus.models.proto import \
    scimag_pb2 as nexus_dot_models_dot_proto_dot_scimag__pb2
from nexus.models.proto import \
    scitech_pb2 as nexus_dot_models_dot_proto_dot_scitech__pb2
from nexus.models.proto import \
    sharience_pb2 as nexus_dot_models_dot_proto_dot_sharience__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='nexus/models/proto/typed_document.proto',
  package='nexus.models.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'nexus/models/proto/typed_document.proto\x12\x12nexus.models.proto\x1a\x1fnexus/models/proto/scimag.proto\x1a nexus/models/proto/scitech.proto\x1a\"nexus/models/proto/sharience.proto\"\xad\x01\n\rTypedDocument\x12,\n\x06scimag\x18\x01 \x01(\x0b\x32\x1a.nexus.models.proto.ScimagH\x00\x12.\n\x07scitech\x18\x02 \x01(\x0b\x32\x1b.nexus.models.proto.ScitechH\x00\x12\x32\n\tsharience\x18\x03 \x01(\x0b\x32\x1d.nexus.models.proto.SharienceH\x00\x42\n\n\x08\x64ocumentb\x06proto3'
  ,
  dependencies=[nexus_dot_models_dot_proto_dot_scimag__pb2.DESCRIPTOR,nexus_dot_models_dot_proto_dot_scitech__pb2.DESCRIPTOR,nexus_dot_models_dot_proto_dot_sharience__pb2.DESCRIPTOR,])




_TYPEDDOCUMENT = _descriptor.Descriptor(
  name='TypedDocument',
  full_name='nexus.models.proto.TypedDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scimag', full_name='nexus.models.proto.TypedDocument.scimag', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scitech', full_name='nexus.models.proto.TypedDocument.scitech', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sharience', full_name='nexus.models.proto.TypedDocument.sharience', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='document', full_name='nexus.models.proto.TypedDocument.document',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=167,
  serialized_end=340,
)

_TYPEDDOCUMENT.fields_by_name['scimag'].message_type = nexus_dot_models_dot_proto_dot_scimag__pb2._SCIMAG
_TYPEDDOCUMENT.fields_by_name['scitech'].message_type = nexus_dot_models_dot_proto_dot_scitech__pb2._SCITECH
_TYPEDDOCUMENT.fields_by_name['sharience'].message_type = nexus_dot_models_dot_proto_dot_sharience__pb2._SHARIENCE
_TYPEDDOCUMENT.oneofs_by_name['document'].fields.append(
  _TYPEDDOCUMENT.fields_by_name['scimag'])
_TYPEDDOCUMENT.fields_by_name['scimag'].containing_oneof = _TYPEDDOCUMENT.oneofs_by_name['document']
_TYPEDDOCUMENT.oneofs_by_name['document'].fields.append(
  _TYPEDDOCUMENT.fields_by_name['scitech'])
_TYPEDDOCUMENT.fields_by_name['scitech'].containing_oneof = _TYPEDDOCUMENT.oneofs_by_name['document']
_TYPEDDOCUMENT.oneofs_by_name['document'].fields.append(
  _TYPEDDOCUMENT.fields_by_name['sharience'])
_TYPEDDOCUMENT.fields_by_name['sharience'].containing_oneof = _TYPEDDOCUMENT.oneofs_by_name['document']
DESCRIPTOR.message_types_by_name['TypedDocument'] = _TYPEDDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypedDocument = _reflection.GeneratedProtocolMessageType('TypedDocument', (_message.Message,), {
  'DESCRIPTOR' : _TYPEDDOCUMENT,
  '__module__' : 'nexus.models.proto.typed_document_pb2'
  # @@protoc_insertion_point(class_scope:nexus.models.proto.TypedDocument)
  })
_sym_db.RegisterMessage(TypedDocument)


# @@protoc_insertion_point(module_scope)
