// source: nexus/models/proto/typed_document.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nexus_models_proto_scimag_pb = require('../../../nexus/models/proto/scimag_pb.js');
goog.object.extend(proto, nexus_models_proto_scimag_pb);
var nexus_models_proto_scitech_pb = require('../../../nexus/models/proto/scitech_pb.js');
goog.object.extend(proto, nexus_models_proto_scitech_pb);
var nexus_models_proto_sharience_pb = require('../../../nexus/models/proto/sharience_pb.js');
goog.object.extend(proto, nexus_models_proto_sharience_pb);
goog.exportSymbol('proto.nexus.models.proto.TypedDocument', null, global);
goog.exportSymbol('proto.nexus.models.proto.TypedDocument.DocumentCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.models.proto.TypedDocument = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.nexus.models.proto.TypedDocument.oneofGroups_);
};
goog.inherits(proto.nexus.models.proto.TypedDocument, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.models.proto.TypedDocument.displayName = 'proto.nexus.models.proto.TypedDocument';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.nexus.models.proto.TypedDocument.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.nexus.models.proto.TypedDocument.DocumentCase = {
  DOCUMENT_NOT_SET: 0,
  SCIMAG: 1,
  SCITECH: 2,
  SHARIENCE: 3
};

/**
 * @return {proto.nexus.models.proto.TypedDocument.DocumentCase}
 */
proto.nexus.models.proto.TypedDocument.prototype.getDocumentCase = function() {
  return /** @type {proto.nexus.models.proto.TypedDocument.DocumentCase} */(jspb.Message.computeOneofCase(this, proto.nexus.models.proto.TypedDocument.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.models.proto.TypedDocument.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.models.proto.TypedDocument.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.models.proto.TypedDocument} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.TypedDocument.toObject = function(includeInstance, msg) {
  var f, obj = {
    scimag: (f = msg.getScimag()) && nexus_models_proto_scimag_pb.Scimag.toObject(includeInstance, f),
    scitech: (f = msg.getScitech()) && nexus_models_proto_scitech_pb.Scitech.toObject(includeInstance, f),
    sharience: (f = msg.getSharience()) && nexus_models_proto_sharience_pb.Sharience.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.models.proto.TypedDocument.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.models.proto.TypedDocument;
  return proto.nexus.models.proto.TypedDocument.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.models.proto.TypedDocument} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.models.proto.TypedDocument.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nexus_models_proto_scimag_pb.Scimag;
      reader.readMessage(value,nexus_models_proto_scimag_pb.Scimag.deserializeBinaryFromReader);
      msg.setScimag(value);
      break;
    case 2:
      var value = new nexus_models_proto_scitech_pb.Scitech;
      reader.readMessage(value,nexus_models_proto_scitech_pb.Scitech.deserializeBinaryFromReader);
      msg.setScitech(value);
      break;
    case 3:
      var value = new nexus_models_proto_sharience_pb.Sharience;
      reader.readMessage(value,nexus_models_proto_sharience_pb.Sharience.deserializeBinaryFromReader);
      msg.setSharience(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.models.proto.TypedDocument.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.models.proto.TypedDocument.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.models.proto.TypedDocument} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.models.proto.TypedDocument.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScimag();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nexus_models_proto_scimag_pb.Scimag.serializeBinaryToWriter
    );
  }
  f = message.getScitech();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      nexus_models_proto_scitech_pb.Scitech.serializeBinaryToWriter
    );
  }
  f = message.getSharience();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      nexus_models_proto_sharience_pb.Sharience.serializeBinaryToWriter
    );
  }
};


/**
 * optional Scimag scimag = 1;
 * @return {?proto.nexus.models.proto.Scimag}
 */
proto.nexus.models.proto.TypedDocument.prototype.getScimag = function() {
  return /** @type{?proto.nexus.models.proto.Scimag} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_scimag_pb.Scimag, 1));
};


/**
 * @param {?proto.nexus.models.proto.Scimag|undefined} value
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
*/
proto.nexus.models.proto.TypedDocument.prototype.setScimag = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.nexus.models.proto.TypedDocument.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
 */
proto.nexus.models.proto.TypedDocument.prototype.clearScimag = function() {
  return this.setScimag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.TypedDocument.prototype.hasScimag = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Scitech scitech = 2;
 * @return {?proto.nexus.models.proto.Scitech}
 */
proto.nexus.models.proto.TypedDocument.prototype.getScitech = function() {
  return /** @type{?proto.nexus.models.proto.Scitech} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_scitech_pb.Scitech, 2));
};


/**
 * @param {?proto.nexus.models.proto.Scitech|undefined} value
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
*/
proto.nexus.models.proto.TypedDocument.prototype.setScitech = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.nexus.models.proto.TypedDocument.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
 */
proto.nexus.models.proto.TypedDocument.prototype.clearScitech = function() {
  return this.setScitech(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.TypedDocument.prototype.hasScitech = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Sharience sharience = 3;
 * @return {?proto.nexus.models.proto.Sharience}
 */
proto.nexus.models.proto.TypedDocument.prototype.getSharience = function() {
  return /** @type{?proto.nexus.models.proto.Sharience} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_sharience_pb.Sharience, 3));
};


/**
 * @param {?proto.nexus.models.proto.Sharience|undefined} value
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
*/
proto.nexus.models.proto.TypedDocument.prototype.setSharience = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.nexus.models.proto.TypedDocument.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.models.proto.TypedDocument} returns this
 */
proto.nexus.models.proto.TypedDocument.prototype.clearSharience = function() {
  return this.setSharience(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.models.proto.TypedDocument.prototype.hasSharience = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.nexus.models.proto);
