---

application:
  debug: true
  # Enable special Postgres `sharience` table to retrieve user-sent files
  is_sharience_enabled: false
  # URL to the picture shown while maintenance
  maintenance_picture_url:
  # Used in logging
  service_name: nexus-hub
  # Parse downloaded document with Grobid
  should_parse_with_grobid: true
  # Store file hashes into operation log
  should_store_hashes: true
database:
  database: nexus
  host:
  password:
  username:
grobid:
  url:
grpc:
  # Listen address
  address: 0.0.0.0
  # Listen port
  port: 82
idm:
  endpoint:
ipfs:
  address: localhost
  port: 4001
log_path: '/var/log/nexus-hub'
meta_api:
  url:
pylon:
  proxies: []
telegram:
  bots:
    _policy: merge
    libgen_scihub_2_bot:
      # Telegram App Hash from https://my.telegram.org/
      app_hash:
      # Telegram App ID from https://my.telegram.org/
      app_id: 00000
      # Internal bot name used in logging
      bot_name: nexus-hub
      bot_token:
      # Telethon database for keeping cache
      database:
        session_id: /tmp/nexus-hub.db
      # Frequency of updating downloading progress
      progress_throttle_seconds: 5
      # Send files using stored telegram_file_id
      should_use_telegram_file_id: true
  related_channel: 'nexus_search'
