---
application:
  debug: true
  service_name: idm-api
clickhouse:
  host:
  password:
  username:
database:
  idm:
    database: nexus
    drivername: postgresql
    host:
    password:
    port: 5432
    username:
  nexus:
    database: nexus
    drivername: postgresql
    host:
    password:
    port: 5432
    username:
grpc:
  address: 0.0.0.0
  port: 82
log_path: '/var/log/idm-api'
