---
application:
  debug: true
  service_name: idm-api
database:
  idm:
    drivername: postgresql
    port: 5432
  nexus:
    drivername: postgresql
    port: 5432
grpc:
  address: 0.0.0.0
  port: 82
log_path: '/var/log/idm-api'
