---
services:
  nexus-cognitron-web:
    environment:
      ENV_TYPE: production
      NEXUS_COGNITRON_WEB_application.address: 0.0.0.0
      NEXUS_COGNITRON_WEB_application.port: 3000
      NEXUS_COGNITRON_WEB_ipfs.gateway.url: https://cloudflare-ipfs.com
    image: thesuperpirate/nexus-cognitron-web:latest
    ports:
      - '3000:3000'
version: "3"
