---

logging:
  disable_existing_loggers: false
  formatters:
    default:
      class: library.logging.formatters.DefaultFormatter
    traceback:
      class: library.logging.formatters.TracebackFormatter
  handlers:
    console:
      class: logging.StreamHandler
      level: WARNING
      stream: 'ext://sys.stderr'
    debug:
      class: library.logging.handlers.BaseFileHandler
      filename: '{{ log_path }}/debug.log'
      formatter: default
      level: DEBUG
    error:
      class: library.logging.handlers.BaseFileHandler
      filename: '{{ log_path }}/error.log'
      formatter: default
      level: ERROR
    statbox:
      class: library.logging.handlers.BaseFileHandler
      filename: '{{ log_path }}/statbox.log'
      formatter: default
      level: INFO
    traceback:
      class: library.logging.handlers.BaseFileHandler
      filename: '{{ log_path }}/traceback.log'
      formatter: traceback
      level: ERROR
    warning:
      class: library.logging.handlers.BaseFileHandler
      filename: '{{ log_path }}/warning.log'
      formatter: default
      level: WARNING
  loggers:
    aiokafka:
      handlers:
        - error
      propagate: false
    asyncio:
      handlers:
        - error
      level: WARNING
    debug:
      handlers:
        - debug
      propagate: false
    error:
      handlers:
        - console
        - error
        - traceback
        - warning
      propagate: false
    statbox:
      handlers:
        - statbox
      propagate: false
  root:
    handlers:
      - console
      - debug
      - error
      - warning
    level: DEBUG
  version: 1
