---

application:
  debug: true
  learn_log: true
  request_id_length: 12
  session_id_length: 8
  threads: 4
grpc:
  host: 0.0.0.0
  port: 82
log_path: '/var/log/nexus-meta-api'
stat_provider:
  enabled: false
summa:
  connection_timeout: 5
  endpoint: summa:82
  ttl_dns_cache: 10
  use_dns_cache: true
