# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexus/meta_api/proto/documents_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nexus.models.proto import \
    typed_document_pb2 as nexus_dot_models_dot_proto_dot_typed__document__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,nexus/meta_api/proto/documents_service.proto\x12\x14nexus.meta_api.proto\x1a\'nexus/models/proto/typed_document.proto\"`\n\x0bRollRequest\x12\x1f\n\x0bindex_alias\x18\x01 \x01(\tR\nindexAlias\x12\x14\n\x05query\x18\x02 \x01(\tR\x05query\x12\x1a\n\x08language\x18\x03 \x01(\tR\x08language\"X\n\x0cRollResponse\x12H\n\x0etyped_document\x18\x01 \x01(\x0b\x32!.nexus.models.proto.TypedDocumentR\rtypedDocument\"b\n\x10TopMissedRequest\x12\x12\n\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n\tpage_size\x18\x02 \x01(\rR\x08pageSize\x12\x1d\n\ndoi_prefix\x18\x03 \x01(\tR\tdoiPrefix\"z\n\x11TopMissedResponse\x12J\n\x0ftyped_documents\x18\x01 \x03(\x0b\x32!.nexus.models.proto.TypedDocumentR\x0etypedDocuments\x12\x19\n\x08has_next\x18\x02 \x01(\x08R\x07hasNext\"\x88\x01\n\x14TypedDocumentRequest\x12\x1f\n\x0bindex_alias\x18\x01 \x01(\tR\nindexAlias\x12\x1f\n\x0b\x64ocument_id\x18\x02 \x01(\x04R\ndocumentId\x12\x1a\n\x08position\x18\x03 \x01(\rR\x08position\x12\x12\n\x04mode\x18\x04 \x01(\tR\x04mode2\x95\x02\n\tDocuments\x12V\n\x03get\x12*.nexus.meta_api.proto.TypedDocumentRequest\x1a!.nexus.models.proto.TypedDocument\"\x00\x12O\n\x04roll\x12!.nexus.meta_api.proto.RollRequest\x1a\".nexus.meta_api.proto.RollResponse\"\x00\x12_\n\ntop_missed\x12&.nexus.meta_api.proto.TopMissedRequest\x1a\'.nexus.meta_api.proto.TopMissedResponse\"\x00\x62\x06proto3')



_ROLLREQUEST = DESCRIPTOR.message_types_by_name['RollRequest']
_ROLLRESPONSE = DESCRIPTOR.message_types_by_name['RollResponse']
_TOPMISSEDREQUEST = DESCRIPTOR.message_types_by_name['TopMissedRequest']
_TOPMISSEDRESPONSE = DESCRIPTOR.message_types_by_name['TopMissedResponse']
_TYPEDDOCUMENTREQUEST = DESCRIPTOR.message_types_by_name['TypedDocumentRequest']
RollRequest = _reflection.GeneratedProtocolMessageType('RollRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROLLREQUEST,
  '__module__' : 'nexus.meta_api.proto.documents_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.RollRequest)
  })
_sym_db.RegisterMessage(RollRequest)

RollResponse = _reflection.GeneratedProtocolMessageType('RollResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROLLRESPONSE,
  '__module__' : 'nexus.meta_api.proto.documents_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.RollResponse)
  })
_sym_db.RegisterMessage(RollResponse)

TopMissedRequest = _reflection.GeneratedProtocolMessageType('TopMissedRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOPMISSEDREQUEST,
  '__module__' : 'nexus.meta_api.proto.documents_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.TopMissedRequest)
  })
_sym_db.RegisterMessage(TopMissedRequest)

TopMissedResponse = _reflection.GeneratedProtocolMessageType('TopMissedResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOPMISSEDRESPONSE,
  '__module__' : 'nexus.meta_api.proto.documents_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.TopMissedResponse)
  })
_sym_db.RegisterMessage(TopMissedResponse)

TypedDocumentRequest = _reflection.GeneratedProtocolMessageType('TypedDocumentRequest', (_message.Message,), {
  'DESCRIPTOR' : _TYPEDDOCUMENTREQUEST,
  '__module__' : 'nexus.meta_api.proto.documents_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.TypedDocumentRequest)
  })
_sym_db.RegisterMessage(TypedDocumentRequest)

_DOCUMENTS = DESCRIPTOR.services_by_name['Documents']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLLREQUEST._serialized_start=111
  _ROLLREQUEST._serialized_end=207
  _ROLLRESPONSE._serialized_start=209
  _ROLLRESPONSE._serialized_end=297
  _TOPMISSEDREQUEST._serialized_start=299
  _TOPMISSEDREQUEST._serialized_end=397
  _TOPMISSEDRESPONSE._serialized_start=399
  _TOPMISSEDRESPONSE._serialized_end=521
  _TYPEDDOCUMENTREQUEST._serialized_start=524
  _TYPEDDOCUMENTREQUEST._serialized_end=660
  _DOCUMENTS._serialized_start=663
  _DOCUMENTS._serialized_end=940
# @@protoc_insertion_point(module_scope)
