// source: nexus/meta_api/proto/documents_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nexus_models_proto_typed_document_pb = require('../../../nexus/models/proto/typed_document_pb.js');
goog.object.extend(proto, nexus_models_proto_typed_document_pb);
goog.exportSymbol('proto.nexus.meta_api.proto.GetViewResponse', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.PutTypedDocumentResponse', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.RollRequest', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.RollResponse', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.TopMissedRequest', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.TopMissedResponse', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.TypedDocumentRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.RollRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.RollRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.RollRequest.displayName = 'proto.nexus.meta_api.proto.RollRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.RollResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.RollResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.RollResponse.displayName = 'proto.nexus.meta_api.proto.RollResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.TopMissedRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.TopMissedRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.TopMissedRequest.displayName = 'proto.nexus.meta_api.proto.TopMissedRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.TopMissedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.meta_api.proto.TopMissedResponse.repeatedFields_, null);
};
goog.inherits(proto.nexus.meta_api.proto.TopMissedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.TopMissedResponse.displayName = 'proto.nexus.meta_api.proto.TopMissedResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.TypedDocumentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.TypedDocumentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.TypedDocumentRequest.displayName = 'proto.nexus.meta_api.proto.TypedDocumentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.PutTypedDocumentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.PutTypedDocumentResponse.displayName = 'proto.nexus.meta_api.proto.PutTypedDocumentResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.GetViewResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.GetViewResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.GetViewResponse.displayName = 'proto.nexus.meta_api.proto.GetViewResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.RollRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.RollRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.RollRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.RollRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    language: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sessionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.RollRequest}
 */
proto.nexus.meta_api.proto.RollRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.RollRequest;
  return proto.nexus.meta_api.proto.RollRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.RollRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.RollRequest}
 */
proto.nexus.meta_api.proto.RollRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.RollRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.RollRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.RollRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.RollRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string language = 1;
 * @return {string}
 */
proto.nexus.meta_api.proto.RollRequest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.RollRequest} returns this
 */
proto.nexus.meta_api.proto.RollRequest.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string session_id = 2;
 * @return {string}
 */
proto.nexus.meta_api.proto.RollRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.RollRequest} returns this
 */
proto.nexus.meta_api.proto.RollRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 user_id = 3;
 * @return {number}
 */
proto.nexus.meta_api.proto.RollRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.RollRequest} returns this
 */
proto.nexus.meta_api.proto.RollRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.RollResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.RollResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.RollResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.RollResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    documentId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.RollResponse}
 */
proto.nexus.meta_api.proto.RollResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.RollResponse;
  return proto.nexus.meta_api.proto.RollResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.RollResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.RollResponse}
 */
proto.nexus.meta_api.proto.RollResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDocumentId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.RollResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.RollResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.RollResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.RollResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocumentId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
};


/**
 * optional uint64 document_id = 1;
 * @return {number}
 */
proto.nexus.meta_api.proto.RollResponse.prototype.getDocumentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.RollResponse} returns this
 */
proto.nexus.meta_api.proto.RollResponse.prototype.setDocumentId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.TopMissedRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.TopMissedRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TopMissedRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    page: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sessionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest}
 */
proto.nexus.meta_api.proto.TopMissedRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.TopMissedRequest;
  return proto.nexus.meta_api.proto.TopMissedRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.TopMissedRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest}
 */
proto.nexus.meta_api.proto.TopMissedRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPage(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPageSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.TopMissedRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.TopMissedRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TopMissedRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPage();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional uint32 page = 1;
 * @return {number}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest} returns this
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 page_size = 2;
 * @return {number}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest} returns this
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string session_id = 3;
 * @return {string}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest} returns this
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 user_id = 4;
 * @return {number}
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TopMissedRequest} returns this
 */
proto.nexus.meta_api.proto.TopMissedRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.meta_api.proto.TopMissedResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.TopMissedResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.TopMissedResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TopMissedResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    typedDocumentsList: jspb.Message.toObjectList(msg.getTypedDocumentsList(),
    nexus_models_proto_typed_document_pb.TypedDocument.toObject, includeInstance),
    hasNext: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.TopMissedResponse}
 */
proto.nexus.meta_api.proto.TopMissedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.TopMissedResponse;
  return proto.nexus.meta_api.proto.TopMissedResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.TopMissedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.TopMissedResponse}
 */
proto.nexus.meta_api.proto.TopMissedResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nexus_models_proto_typed_document_pb.TypedDocument;
      reader.readMessage(value,nexus_models_proto_typed_document_pb.TypedDocument.deserializeBinaryFromReader);
      msg.addTypedDocuments(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasNext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.TopMissedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.TopMissedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TopMissedResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypedDocumentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      nexus_models_proto_typed_document_pb.TypedDocument.serializeBinaryToWriter
    );
  }
  f = message.getHasNext();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * repeated nexus.models.proto.TypedDocument typed_documents = 1;
 * @return {!Array<!proto.nexus.models.proto.TypedDocument>}
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.getTypedDocumentsList = function() {
  return /** @type{!Array<!proto.nexus.models.proto.TypedDocument>} */ (
    jspb.Message.getRepeatedWrapperField(this, nexus_models_proto_typed_document_pb.TypedDocument, 1));
};


/**
 * @param {!Array<!proto.nexus.models.proto.TypedDocument>} value
 * @return {!proto.nexus.meta_api.proto.TopMissedResponse} returns this
*/
proto.nexus.meta_api.proto.TopMissedResponse.prototype.setTypedDocumentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.nexus.models.proto.TypedDocument=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.addTypedDocuments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.nexus.models.proto.TypedDocument, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.meta_api.proto.TopMissedResponse} returns this
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.clearTypedDocumentsList = function() {
  return this.setTypedDocumentsList([]);
};


/**
 * optional bool has_next = 2;
 * @return {boolean}
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.getHasNext = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.meta_api.proto.TopMissedResponse} returns this
 */
proto.nexus.meta_api.proto.TopMissedResponse.prototype.setHasNext = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.TypedDocumentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.TypedDocumentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    schema: jspb.Message.getFieldWithDefault(msg, 1, ""),
    documentId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    position: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sessionId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.TypedDocumentRequest;
  return proto.nexus.meta_api.proto.TypedDocumentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.TypedDocumentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSchema(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDocumentId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPosition(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.TypedDocumentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.TypedDocumentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchema();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDocumentId();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getPosition();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string schema = 1;
 * @return {string}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.getSchema = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest} returns this
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.setSchema = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 document_id = 2;
 * @return {number}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.getDocumentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest} returns this
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.setDocumentId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 position = 3;
 * @return {number}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.getPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest} returns this
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.setPosition = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string session_id = 4;
 * @return {string}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest} returns this
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 user_id = 5;
 * @return {number}
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.TypedDocumentRequest} returns this
 */
proto.nexus.meta_api.proto.TypedDocumentRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.PutTypedDocumentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.PutTypedDocumentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.PutTypedDocumentResponse}
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.PutTypedDocumentResponse;
  return proto.nexus.meta_api.proto.PutTypedDocumentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.PutTypedDocumentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.PutTypedDocumentResponse}
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.PutTypedDocumentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.PutTypedDocumentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.PutTypedDocumentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.GetViewResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.GetViewResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.GetViewResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    typedDocument: (f = msg.getTypedDocument()) && nexus_models_proto_typed_document_pb.TypedDocument.toObject(includeInstance, f),
    filedata: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filename: jspb.Message.getFieldWithDefault(msg, 3, ""),
    filesize: jspb.Message.getFieldWithDefault(msg, 4, ""),
    firstAuthors: jspb.Message.getFieldWithDefault(msg, 5, ""),
    locator: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.GetViewResponse}
 */
proto.nexus.meta_api.proto.GetViewResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.GetViewResponse;
  return proto.nexus.meta_api.proto.GetViewResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.GetViewResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.GetViewResponse}
 */
proto.nexus.meta_api.proto.GetViewResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nexus_models_proto_typed_document_pb.TypedDocument;
      reader.readMessage(value,nexus_models_proto_typed_document_pb.TypedDocument.deserializeBinaryFromReader);
      msg.setTypedDocument(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFiledata(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilesize(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstAuthors(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocator(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.GetViewResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.GetViewResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.GetViewResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypedDocument();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nexus_models_proto_typed_document_pb.TypedDocument.serializeBinaryToWriter
    );
  }
  f = message.getFiledata();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFilesize();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFirstAuthors();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLocator();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional nexus.models.proto.TypedDocument typed_document = 1;
 * @return {?proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getTypedDocument = function() {
  return /** @type{?proto.nexus.models.proto.TypedDocument} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_typed_document_pb.TypedDocument, 1));
};


/**
 * @param {?proto.nexus.models.proto.TypedDocument|undefined} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
*/
proto.nexus.meta_api.proto.GetViewResponse.prototype.setTypedDocument = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.clearTypedDocument = function() {
  return this.setTypedDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.hasTypedDocument = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string filedata = 2;
 * @return {string}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getFiledata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.setFiledata = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string filename = 3;
 * @return {string}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string filesize = 4;
 * @return {string}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getFilesize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.setFilesize = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string first_authors = 5;
 * @return {string}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getFirstAuthors = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.setFirstAuthors = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string locator = 6;
 * @return {string}
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.getLocator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.GetViewResponse} returns this
 */
proto.nexus.meta_api.proto.GetViewResponse.prototype.setLocator = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.nexus.meta_api.proto);
