// source: nexus/meta_api/proto/search_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nexus_models_proto_typed_document_pb = require('../../../nexus/models/proto/typed_document_pb.js');
goog.object.extend(proto, nexus_models_proto_typed_document_pb);
goog.exportSymbol('proto.nexus.meta_api.proto.ScoredDocument', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.SearchRequest', null, global);
goog.exportSymbol('proto.nexus.meta_api.proto.SearchResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.ScoredDocument = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nexus.meta_api.proto.ScoredDocument, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.ScoredDocument.displayName = 'proto.nexus.meta_api.proto.ScoredDocument';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.SearchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.meta_api.proto.SearchResponse.repeatedFields_, null);
};
goog.inherits(proto.nexus.meta_api.proto.SearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.SearchResponse.displayName = 'proto.nexus.meta_api.proto.SearchResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nexus.meta_api.proto.SearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nexus.meta_api.proto.SearchRequest.repeatedFields_, null);
};
goog.inherits(proto.nexus.meta_api.proto.SearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nexus.meta_api.proto.SearchRequest.displayName = 'proto.nexus.meta_api.proto.SearchRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.ScoredDocument.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.ScoredDocument} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.ScoredDocument.toObject = function(includeInstance, msg) {
  var f, obj = {
    typedDocument: (f = msg.getTypedDocument()) && nexus_models_proto_typed_document_pb.TypedDocument.toObject(includeInstance, f),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    position: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.ScoredDocument}
 */
proto.nexus.meta_api.proto.ScoredDocument.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.ScoredDocument;
  return proto.nexus.meta_api.proto.ScoredDocument.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.ScoredDocument} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.ScoredDocument}
 */
proto.nexus.meta_api.proto.ScoredDocument.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nexus_models_proto_typed_document_pb.TypedDocument;
      reader.readMessage(value,nexus_models_proto_typed_document_pb.TypedDocument.deserializeBinaryFromReader);
      msg.setTypedDocument(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.ScoredDocument.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.ScoredDocument} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.ScoredDocument.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypedDocument();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nexus_models_proto_typed_document_pb.TypedDocument.serializeBinaryToWriter
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getPosition();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional nexus.models.proto.TypedDocument typed_document = 1;
 * @return {?proto.nexus.models.proto.TypedDocument}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.getTypedDocument = function() {
  return /** @type{?proto.nexus.models.proto.TypedDocument} */ (
    jspb.Message.getWrapperField(this, nexus_models_proto_typed_document_pb.TypedDocument, 1));
};


/**
 * @param {?proto.nexus.models.proto.TypedDocument|undefined} value
 * @return {!proto.nexus.meta_api.proto.ScoredDocument} returns this
*/
proto.nexus.meta_api.proto.ScoredDocument.prototype.setTypedDocument = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nexus.meta_api.proto.ScoredDocument} returns this
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.clearTypedDocument = function() {
  return this.setTypedDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.hasTypedDocument = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.ScoredDocument} returns this
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional uint32 position = 3;
 * @return {number}
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.getPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.ScoredDocument} returns this
 */
proto.nexus.meta_api.proto.ScoredDocument.prototype.setPosition = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.meta_api.proto.SearchResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.SearchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.SearchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.SearchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    scoredDocumentsList: jspb.Message.toObjectList(msg.getScoredDocumentsList(),
    proto.nexus.meta_api.proto.ScoredDocument.toObject, includeInstance),
    hasNext: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.SearchResponse}
 */
proto.nexus.meta_api.proto.SearchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.SearchResponse;
  return proto.nexus.meta_api.proto.SearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.SearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.SearchResponse}
 */
proto.nexus.meta_api.proto.SearchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.nexus.meta_api.proto.ScoredDocument;
      reader.readMessage(value,proto.nexus.meta_api.proto.ScoredDocument.deserializeBinaryFromReader);
      msg.addScoredDocuments(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasNext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.SearchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.SearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.SearchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScoredDocumentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.nexus.meta_api.proto.ScoredDocument.serializeBinaryToWriter
    );
  }
  f = message.getHasNext();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * repeated ScoredDocument scored_documents = 1;
 * @return {!Array<!proto.nexus.meta_api.proto.ScoredDocument>}
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.getScoredDocumentsList = function() {
  return /** @type{!Array<!proto.nexus.meta_api.proto.ScoredDocument>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nexus.meta_api.proto.ScoredDocument, 1));
};


/**
 * @param {!Array<!proto.nexus.meta_api.proto.ScoredDocument>} value
 * @return {!proto.nexus.meta_api.proto.SearchResponse} returns this
*/
proto.nexus.meta_api.proto.SearchResponse.prototype.setScoredDocumentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.nexus.meta_api.proto.ScoredDocument=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nexus.meta_api.proto.ScoredDocument}
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.addScoredDocuments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.nexus.meta_api.proto.ScoredDocument, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.meta_api.proto.SearchResponse} returns this
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.clearScoredDocumentsList = function() {
  return this.setScoredDocumentsList([]);
};


/**
 * optional bool has_next = 2;
 * @return {boolean}
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.getHasNext = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nexus.meta_api.proto.SearchResponse} returns this
 */
proto.nexus.meta_api.proto.SearchResponse.prototype.setHasNext = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nexus.meta_api.proto.SearchRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nexus.meta_api.proto.SearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nexus.meta_api.proto.SearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.SearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    schemasList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    query: jspb.Message.getFieldWithDefault(msg, 2, ""),
    page: jspb.Message.getFieldWithDefault(msg, 3, 0),
    pageSize: jspb.Message.getFieldWithDefault(msg, 4, 0),
    language: jspb.Message.getFieldWithDefault(msg, 5, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    sessionId: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nexus.meta_api.proto.SearchRequest}
 */
proto.nexus.meta_api.proto.SearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nexus.meta_api.proto.SearchRequest;
  return proto.nexus.meta_api.proto.SearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nexus.meta_api.proto.SearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nexus.meta_api.proto.SearchRequest}
 */
proto.nexus.meta_api.proto.SearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addSchemas(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPage(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPageSize(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nexus.meta_api.proto.SearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nexus.meta_api.proto.SearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nexus.meta_api.proto.SearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchemasList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * repeated string schemas = 1;
 * @return {!Array<string>}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getSchemasList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setSchemasList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.addSchemas = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.clearSchemasList = function() {
  return this.setSchemasList([]);
};


/**
 * optional string query = 2;
 * @return {string}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 page = 3;
 * @return {number}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 page_size = 4;
 * @return {number}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string language = 5;
 * @return {string}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 user_id = 6;
 * @return {number}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string session_id = 7;
 * @return {string}
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.nexus.meta_api.proto.SearchRequest} returns this
 */
proto.nexus.meta_api.proto.SearchRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.nexus.meta_api.proto);
