# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexus/meta_api/proto/search_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nexus.models.proto import \
    typed_document_pb2 as nexus_dot_models_dot_proto_dot_typed__document__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)nexus/meta_api/proto/search_service.proto\x12\x14nexus.meta_api.proto\x1a\'nexus/models/proto/typed_document.proto\"\x8c\x01\n\x0eScoredDocument\x12H\n\x0etyped_document\x18\x01 \x01(\x0b\x32!.nexus.models.proto.TypedDocumentR\rtypedDocument\x12\x14\n\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n\x08position\x18\x03 \x01(\rR\x08position\"\xc1\x01\n\rSearchRequest\x12#\n\rindex_aliases\x18\x01 \x03(\tR\x0cindexAliases\x12\x14\n\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n\tpage_size\x18\x04 \x01(\rR\x08pageSize\x12\x1a\n\x08language\x18\x05 \x01(\tR\x08language\x12(\n\x10with_user_intent\x18\x06 \x01(\x08R\x0ewithUserIntent\"\x92\x01\n\x0eSearchResponse\x12O\n\x10scored_documents\x18\x01 \x03(\x0b\x32$.nexus.meta_api.proto.ScoredDocumentR\x0fscoredDocuments\x12\x19\n\x08has_next\x18\x02 \x01(\x08R\x07hasNext\x12\x14\n\x05\x63ount\x18\x03 \x01(\rR\x05\x63ount2_\n\x06Search\x12U\n\x06search\x12#.nexus.meta_api.proto.SearchRequest\x1a$.nexus.meta_api.proto.SearchResponse\"\x00\x62\x06proto3')



_SCOREDDOCUMENT = DESCRIPTOR.message_types_by_name['ScoredDocument']
_SEARCHREQUEST = DESCRIPTOR.message_types_by_name['SearchRequest']
_SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['SearchResponse']
ScoredDocument = _reflection.GeneratedProtocolMessageType('ScoredDocument', (_message.Message,), {
  'DESCRIPTOR' : _SCOREDDOCUMENT,
  '__module__' : 'nexus.meta_api.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.ScoredDocument)
  })
_sym_db.RegisterMessage(ScoredDocument)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'nexus.meta_api.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'nexus.meta_api.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:nexus.meta_api.proto.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)

_SEARCH = DESCRIPTOR.services_by_name['Search']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREDDOCUMENT._serialized_start=109
  _SCOREDDOCUMENT._serialized_end=249
  _SEARCHREQUEST._serialized_start=252
  _SEARCHREQUEST._serialized_end=445
  _SEARCHRESPONSE._serialized_start=448
  _SEARCHRESPONSE._serialized_end=594
  _SEARCH._serialized_start=596
  _SEARCH._serialized_end=691
# @@protoc_insertion_point(module_scope)
