from . import (
    aboutus,
    admin,
    ban,
    close,
    copyright,
    download,
    help,
    howtohelp,
    legacy,
    noop,
    rank,
    roll,
    search,
    seed,
    settings,
    shortlink,
    start,
    stop,
    submit,
    view,
    vote,
)

__all__ = ['aboutus', 'admin', 'ban', 'copyright', 'close', 'download', 'help', 'howtohelp',
           'legacy', 'noop', 'rank', 'roll', 'search', 'seed', 'settings',
           'shortlink', 'start', 'stop', 'submit', 'view', 'vote']
